### ISSUE TITLE
Not an "issue", just a "thank you"!

### ISSUE THREAD

**Issue by dajare** [RolandTi/shaarli-stack#1]
The title says it all, really. :) 

But I thought I would note, too, that I just added a link to this project at [Shaarli issue #1328](https://github.com/shaarli/Shaarli/issues/1328), "'Compact' link list view". Once or twice I've thought I would try to come up with a "compact" listing (think old del.icio.us, or Pinboard), but lacked the skills. I think "Shaarli Stack" works very nicely for this, and is up there with Kalvn's Material theme as a welcome addition to enhance Shaarli.

So, thank you!

**Comment by RolandTi** [comment]
You're welcome ! Thanks you for your comment :-)

**Comment by nodiscc** [comment]
I also started using this template today and it looks great. Thanks for your work on this.

**Comment by RolandTi** [comment]
> I also started using this template today and it looks great. Thanks for your work on this.

Feel free to comment for any improvements !
