### ISSUE TITLE
Width issue with lots of tags

### ISSUE THREAD

**Issue by triplingual** [RolandTi/shaarli-stack#10]
I'm new to Shaarli and this may be a me problem, but for links with lots of tags (most common on my cooking bookmarks), it would be nice if the links could wrap to be on multiple lines. By coincidence, I have three recent links next to each other that show what Stack looks like with many tags, a moderate number of tags, and a small number of tags.

![Screen Shot 2024-11-01 at 22 37 51](https://github.com/user-attachments/assets/b1b3d6b6-291d-45c5-b5fa-4d77867b7806)

**Comment by triplingual** [comment]
Generally speaking, thanks for this theme though. It's nice!

**Comment by RolandTi** [comment]
Hello,
thanks for your help ! Have a nice day :-)
