### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by bmp** [RolandTi/shaarli-stack#9]
Thank you for the theme, I love it completely. I am trying to style it ala Nord, and currently with the limited options that `default colors` in this manner,

![Screenshot_20240608_150848](https://github.com/RolandTi/shaarli-stack/assets/1095177/76ebcaaf-e503-4143-a8aa-71186d990bbb)

I have two questions:
1. What is the specific value CSS value to edit to change the colour for the highlighted link/bookmark. Only that colour is way off for now. Is there a modular way to set the theme to [nord](https://www.nordtheme.com/docs/usage/) for example?
2. I prefer to use serif fonts, is the settings in this chunk enough to modify? https://github.com/RolandTi/shaarli-stack/blob/dcb50fe632ad182ebb459fd8d12cdb99a725f7b1/stack/css/stack.css#L41-L71

**Comment by RolandTi** [comment]
Hello @bmp, thanks for your comment.

1. The value that define `.linklist-item:hover` is `--accent-color` : https://github.com/RolandTi/shaarli-stack/blob/dcb50fe632ad182ebb459fd8d12cdb99a725f7b1/stack/css/stack.css#L2330-L2332 You can define a new variable in your /data/user.css file if you want a different color from `--accent-color`
2. For the font-face display, you can overwrite the three variable located at the bottom of the file : https://github.com/RolandTi/shaarli-stack/blob/dcb50fe632ad182ebb459fd8d12cdb99a725f7b1/stack/css/stack.css#L22-L24

The best way to override Stack's css is a new file in data/user.css so you can keep updating Stack. Like on this shaarli : https://index.rolandtisserand.fr/data/user.css

**Comment by bmp** [comment]
Got it, would changing the header mean I would lose it in an update? What I mean is the following, this is the list of links. I would like to change first one to the index/main page and remove the third entry. 

![Screenshot 2024-06-10 at 22-49-44 Around the web](https://github.com/RolandTi/shaarli-stack/assets/1095177/8199b871-71f3-4dd9-af6c-c1ab4ab6080a)

**Comment by RolandTi** [comment]
If you edit the html, yes you _could_ lose it, but honestly I will now only follow Shaarli's updates. The theme is finished to me.

**Comment by bmp** [comment]
Thank you for the details.

**Comment by bmp** [comment]
> The best way to override Stack's css is a new file in data/user.css so you can keep updating Stack. Like on this shaarli : https://index.rolandtisserand.fr/data/user.css

I have created a user.css, but it is not being loaded. Do I have to modify a specific file for it?

**Comment by RolandTi** [comment]
There is some issue for user.css : https://github.com/shaarli/Shaarli/issues?q=is%3Aissue+user.css
Mainly because of user rights. My user.css is chmod 664 and my data folder 775

**Comment by bmp** [comment]
Thank you! That did it.
